apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-frontend
  labels:
    app: test-app
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: test-app-frontend
          image: ptanlam/test-frontend:3.2
          resources:
            limits:
              cpu: '200m'
              memory: '128Mi'
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-frontend
spec:
  selector:
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
